### ISSUE TITLE
GitLab Runner on WSL + GitBook project (2)

### ISSUE THREAD

**Issue by NaClYen** [NaClYen/blog#49]
續 #48 這篇記錄一下 GitBook 專案遇到的問題

---

## .gitlab-ci.yml 初始設定

```yaml=
# requiring the environment of NodeJS 10
image: node:10

# add 'node_modules' to cache for speeding up builds
cache:
  paths:
    - node_modules/ # Node modules and dependencies

before_script:
  - npm install gitbook-cli -g # install gitbook
  - gitbook fetch 3.2.3 # fetch final stable version
  - gitbook install # add any requested plugins in book.json

test:
  stage: test
  script:
    - gitbook build . public # build to public path
  only:
    - branches # this job will affect every branch except 'master'
  except:
    - master
    
# the 'pages' job will deploy and build your site to the 'public' path
pages:
  stage: deploy
  script:
    - gitbook build . public # build to public path
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master # this job will affect only the 'master' branch

```
這是 `Create from template` > `Pages/GitBook` 會產生的基礎文件之一.  
接下來操作會基於這份設定, 所以請優先確認你執行當下的版本差異~

---

## 安裝 node js & npm

GitBook 需要 nodejs 的環境, 必裝.  
根據 yml 檔案的設定:  
```yaml=
# requiring the environment of NodeJS 10
image: node:10
```
在 [Node.js Binary Distributions](https://github.com/nodesource/distributions/blob/master/README.md) 裡面找到 `v10.x` 的節點:
```
# Using Ubuntu
curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
sudo apt-get install -y nodejs
```

之後看到類似 `TypeError: cb.apply is not a function` 的錯誤, 八成是 nodejs 的版本不合.  
我在 `v12.x` & `v14.x` 都可觸發這樣的錯誤...

如果你的環境有需要多個版本存在, 推薦使用NVM管理.  
參考 [nvm：安裝、切換不同 Node.js 版本的管理器](https://titangene.github.io/article/nvm.html)

---

### 錯誤
```
$ npm install gitbook-cli -g
npm WARN checkPermissions Missing write access to /usr/local/lib
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gitlab-runner/.npm/_logs/2020-08-06T05_23_00_726Z-debug.log
```

根據錯誤以及觀察 yml 檔內的設定:
```yaml=
before_script:
  - npm install gitbook-cli -g # install gitbook
  - gitbook fetch 3.2.3 # fetch final stable version
  - gitbook install # add any requested plugins in book.json
```
理論上 `gitbook-cli` 不會常常需要更新.  
在身為 Windows 腦殘使用者的我各種權限亂調整之後, 最後決定簡單地繞開問題!  
就把它抽出來在WSL直接一次性安裝吧~~  

### 執行
```bash=
sudo npm install gitbook-cli -g
```

接著用 `#` 註解掉 yml 內的 script, 就沒有煩人的存取權限問題惹~  

```yaml=
before_script:
  #- npm install gitbook-cli -g # install gitbook
  - gitbook fetch 3.2.3 # fetch final stable version
  - gitbook install # add any requested plugins in book.json
```

###### tags: `gitlab` `gitbook` `ubuntu` `linux` `npm` `nodejs` `wsl`
